name: Build and Upload Angular Static Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app for GitHub Pages
        run: npm run build:pages

      - name: Upload static site artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: './docs/browser' # Uploads content from browser subfolder as root
